<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'ExtJsTypes\\Button' => '/Button.php',
                'ExtJsTypes\\Columns' => '/Columns.php',
                'ExtJsTypes\\ComboBox' => '/ComboBox.php',
                'ExtJsTypes\\Data' => '/Data.php',
                'ExtJsTypes\\Fields' => '/Fields.php',
                'ExtJsTypes\\Form' => '/Form.php',
                'ExtJsTypes\\Grid' => '/Grid.php',
                'ExtJsTypes\\Helper\\Response' => '/Helper/Response.php',
                'ExtJsTypes\\ItemsDocker' => '/ItemsDocker.php',
                'ExtJsTypes\\Models\\Base' => '/Models/Base.php',
                'ExtJsTypes\\Models\\Node' => '/Models/Node.inc.php',
                'ExtJsTypes\\Models\\QuestionTemplate' => '/Models/QuestionTemplate.php',
                'ExtJsTypes\\Models\\Response' => '/Models/Response.php',
                'ExtJsTypes\\Models\\TemplateList' => '/Models/TemplateList.php',
                'ExtJsTypes\\Models\\TreeChildren' => '/Models/TreeChildren.php',
                'ExtJsTypes\\Preparable' => '/Preparable.php',
                'ExtJsTypes\\TextField' => '/TextField.php',
                'ExtJsTypes\\ToolBar' => '/ToolBar.php',
                'ExtJsTypes\\Base' => '/Base.php',
                'ExtJsTypes\\VTypes\\Alpha' => '/VTypes/Alpha.php',
                'ExtJsTypes\\VTypes\\Alphanum' => '/VTypes/Alphanum.php',
                'ExtJsTypes\\VTypes\\Base' => '/VTypes/Base.php',
                'ExtJsTypes\\VTypes\\Email' => '/VTypes/Email.php',
                'ExtJsTypes\\VTypes\\Url' => '/VTypes/Url.php'
            );
        }
        if (isset($classes[$class])) {
            require __DIR__ . DIRECTORY_SEPARATOR . 'src'. $classes[$class];
        }

      return false;
     }
);
// @codeCoverageIgnoreEnd